name: Deploy static site to Azure Web App - robotize-flights

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip files for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: release.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1F526C0588B8437693CA3150A87F2DE8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5FB08420E01549E78923C4B4440FFD16 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3AEBDDA508C048ABA2F4803586AFECEB }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'robotize-flights'
          slot-name: 'Production'
          package: .
